name: CI

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 2.7 with Rails 6.1 (minimum supported versions)
          - ruby: '2.7'
            rails: '6.1'
            os: ubuntu-22.04
          # Ruby 3.0 with Rails 7.0
          - ruby: '3.0'
            rails: '7.0'
            os: ubuntu-latest
          # Ruby 3.1 with Rails 7.1
          - ruby: '3.1'
            rails: '7.1'
            os: ubuntu-latest
          # Ruby 3.2 with Rails 7.2
          - ruby: '3.2'
            rails: '7.2'
            os: ubuntu-latest
          # Ruby 3.3 with Rails 8.0
          - ruby: '3.3'
            rails: '8.0'
            os: ubuntu-latest

    env:
      RAILS_VERSION: ${{ matrix.rails }}
      CI: true

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec spec/prosopite_todo/ spec/prosopite_todo_spec.rb

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: matrix.ruby == '3.3' && matrix.rails == '8.0'
        with:
          name: coverage-report
          path: coverage/
          retention-days: 14
